// Embeds the built panel and icon into src/generated/assets.ts so the server
// is one self-contained bundle (no file reads at runtime — serverless friendly).
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";

const root = new URL("..", import.meta.url);
const panelPath = new URL("dist/app/index.html", root);
const html = existsSync(panelPath)
  ? readFileSync(panelPath, "utf8")
  : "<!doctype html><html><body><p>JobPaper panel not built. Run npm run build.</p></body></html>";
const icon = readFileSync(new URL("assets/icon.svg", root), "utf8").trim();
mkdirSync(new URL("src/generated/", root), { recursive: true });
writeFileSync(
  new URL("src/generated/assets.ts", root),
  `// Generated by scripts/gen-assets.mjs. Do not edit.\nexport const PANEL_HTML: string = ${JSON.stringify(html)};\nexport const ICON_SVG: string = ${JSON.stringify(icon)};\n`,
);
console.log(`assets: panel ${(html.length / 1024).toFixed(1)} KB${existsSync(panelPath) ? "" : " (placeholder)"}`);
